name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint Server
        run: npm run lint:server

      - name: Lint Webapp
        run: npm run lint:webapp

      - name: Build Server
        run: npm run build:server

      - name: Build Webapp
        run: npm run build:webapp
